package/utility/DefaultUtilityStyles.ts
addes PX tag to borders in DefaultUtilityStyles
Ref #23
=> refactor(global): :sparkles: addes PX tag to borders

package-lock.json, package.json, package/package-lock.json, package/package.json
add missing keys, author, license, in package.json
Ref: wrappid/styles #30
=> docs(config): :memo: add missing keys in package.json

package/base/BaseStyle.ts, package/context/WrappidContext.ts, package/context/WrappidSyncer.tsx, package/theme/theme.ts, package/theme/themeType.ts
theme related issue fix
Ref #34
=> fix(core): :art: theme related issue fix

package/context/WrappidSyncer.tsx, package/theme/theme.ts, package/theme/themeType.ts
removed spaces from the keys of theme and themeType also added data.default theme to WrappidSyncer.tsx
Ref #36
=> fix(global): :bug: removed spaces from the keys of theme and themeType

package/StylesProvider.tsx
create instances of different CoreStyles of largeCoreStyles, mediumCoreStyles, smallCoreStyles, xLargeCoreStyles, xxLargeCoreStyles in stylesProvider.tsx file.
ref: #42
=> feat: :sparkles: create instances of different Corestyles

package/StylesProvider.tsx, package/base/BaseStyle.ts, package/context/WrappidContext.ts
theme properties not changing issue resolved in styles package
ref #45
=> fix(core): :bug: theme properties not changing issue resolved

package/utility/DefaultUtilityStyles.ts, package/utility/UtilityClasses.ts
add styles for AspectRation of different screens
ref: #53
=> feat(core): :sparkles: add styles for AspectRation

ATTRIBUTIONS.md, package/styledComponents/DefaultSCStyles.ts, scripts/attributions.gen.js
Add functionality in attribution generation script to add fixed header.
#58
=> enhancement: header in attribution script

package-lock.json
Fix runtime security issues, update package-lock.json to patched packages
#60
=> chore(config): :lock: fix runtime security issues

package/styledComponents/DefaultSCStyles.ts
fontsize of corelink is removed
Ref: #62
=> fix: :bug: fontsize of corelink is removed

.github/workflows/pr-guardrails.yml, package/styledComponents/DefaultSCStyles.ts
**Description**
PR guardrails eslint not linting deleted files anymore
ref: #66
=> bugfix: :bug: fix eslint pr guardrails

.github/workflows/pr-guardrails.yml, CHANGELOG.md, package-lock.json, package.json, package/package-lock.json, package/package.json, package/styledComponents/DefaultSCStyles.ts, package/utility/UtilityClasses.ts
added aspect ratio for samsung galaxy fold
Ref #53
=> enhancement: added aspect ratio for samsung galaxy fold

package/context/WrappidContext.ts, package/context/WrappidSyncer.tsx, package/context/wrappidAction.ts, package/context/wrappidReducer.ts, package/index.ts
data syncer related changes
Ref #28
=> feat(core): :fire: data syncer related changes

package/utility/DefaultUtilityStyles.ts, package/utility/UtilityClasses.ts
created styles for transform rotate css property.
ref: #72
=> enhancement: created styles for transform rotate

package/utility/DefaultUtilityStyles.ts, package/utility/UtilityClasses.ts
bug fixed for bg dotted background styles and a text styles css
=> bug fixed for bg dotted background styles and a text styles css

package/utility/DefaultUtilityStyles.ts, package/utility/UtilityClasses.ts
added different bg-grid styles added different bg-grid styles in utilityClasses
ref: #57
=> feat(global): :sparkles: added different bg-grid styles added different bg-grid styles in utilityClasses

package/utility/DefaultUtilityStyles.ts, package/utility/UtilityClasses.ts
added styles of font-weight, line-height and word-spacing
=> styles for font-weight, line-height and word-spacing

package/utility/UtilityClasses.ts
correct the styles object structure
ref: #72
=> refactor(core): :recycle: correct the styles object structure

package/base/constants.ts, package/utility/DefaultUtilityStyles.ts
add a default value for word spacing
ref: #72
=> refactor(global): :recycle: add a default value for word spacing

package/index.ts
exported DEFAULT_THEME constant
ref: #55
=> refactor(core): :recycle: exported DEFAULT_THEME constant

package/base/constants.ts, package/utility/DefaultUtilityStyles.ts, package/utility/UtilityClasses.ts
bugfix: transform rotate not working issue resolved
=> bugfix: transform rotate not working issue resolved

package/utility/DefaultUtilityStyles.ts, package/utility/LargeUtilityStyles.ts, package/utility/MediumUtilityStyles.ts, package/utility/SmallUtilityStyles.ts, package/utility/XLargeUtilityStyles.ts, package/utility/XXLargeUtilityStyles.ts
display property not working so use important
Ref: #89
=> fix: :bug: use important in display property

package/utility/DefaultUtilityStyles.ts
add important to PADDING p0, pr1
Ref: #91
=> feat(global): :sparkles: add important to PADDING

package/StylesProvider.tsx, package/styledComponents/DefaultSCStyles.ts
page theme merge with default theme
Ref: #93
=> fix(global): :sparkles: page theme merge with default theme

package/utility/DefaultUtilityStyles.ts
added important to bgSuccess, bgInfo, bgWarning, bgError. Refer #97 for more information.
---
=> fix(utils): :lipstick: add important to bg

package/utility/DefaultUtilityStyles.ts
add important to backgound in DefaultUtilityStyles
Ref: #105
Clearly describe the changes you've made in this pull request. Explain the purpose and reasoning behind the changes. Reference any relevant issues or discussions using keywords like "Fixes #<issue_number>" or "Resolves #<issue_number>".
---
=> fix(core): :bug: add important to backgound in DefaultUtilityStyles
